redirectsOrigin = "config"
headers = []

[functions]

[functions."*"]
node_bundler = "esbuild"

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/Users/raniophir/travelsure-1/buyinsnew/.next"
publishOrigin = "ui"
commandOrigin = "config"
base = "/Users/raniophir/travelsure-1/buyinsnew"
command = "npm run build"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/buyinsnew/_next/image*"
to = "/.netlify/builders/_ipx"
status = 200.0
force = true

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]