import type { HealthConditionGroup } from "./types";

export const HEALTH_CONDITION_GROUPS: HealthConditionGroup[] = [
  {
    id: "nervous",
    titleHe: "מערכת העצבים",
    titleEn: "The nervous system",
    noteHe: "אם ענית כן — יש לצרף מכתב עדכני מנוירולוג מטפל.",
    noteEn: 'If "Yes" — attach an up-to-date letter from the attending neurologist.',
    options: [
      { id: "stroke", labelHe: "שבץ מוחי", labelEn: "Cerebrovascular accident (stroke)" },
      { id: "epilepsy", labelHe: "אפילפסיה", labelEn: "Epilepsy" },
      { id: "ms", labelHe: "טרשת נפוצה", labelEn: "Multiple sclerosis" },
      { id: "muscular", labelHe: "ניוון שרירים / מחלה אטרופית", labelEn: "Muscular dystrophy or other atrophic disease" },
      { id: "dizziness", labelHe: "סחרחורות חוזרות", labelEn: "Reoccurring dizziness" },
      { id: "headaches", labelHe: "כאבי ראש", labelEn: "Headaches" },
      { id: "balance", labelHe: "הפרעות שיווי משקל", labelEn: "Balance disorders" },
      { id: "fainting", labelHe: "עילפון", labelEn: "Fainting" },
      { id: "parkinson", labelHe: "פרקינסון", labelEn: "Parkinson's syndrome" },
      { id: "alzheimer", labelHe: "אלצהיימר", labelEn: "Alzheimer's disease" },
      { id: "trembling", labelHe: "רעד", labelEn: "Trembling" },
      { id: "retardation", labelHe: "פיגור שכלי", labelEn: "Mental retardation" },
      { id: "autism", labelHe: "אוטיזם", labelEn: "Autism" },
      { id: "down", labelHe: "תסמונת דאון", labelEn: "Down's syndrome" },
      { id: "cp", labelHe: "שיתוק מוחין", labelEn: "Cerebral palsy" },
      { id: "polio", labelHe: "פוליו", labelEn: "Poliomyelitis (infantile paralysis)" },
      { id: "gaucher", labelHe: "מחלת גושה", labelEn: "Gaucher's disease" },
      { id: "numbness", labelHe: "אובדן תחושה", labelEn: "Loss of sensation (numbness)" },
      { id: "adhd", labelHe: "הפרעות קשב", labelEn: "Attention deficit disorders" },
      { id: "migraine", labelHe: "מיגרנה", labelEn: "Migraine" },
      { id: "dementia", labelHe: "ירידה בזיכרון / דמנציה", labelEn: "Declined memory (dementia)" },
      { id: "aids", labelHe: "AIDS", labelEn: "AIDS" },
      { id: "hiv", labelHe: "נשא HIV", labelEn: "HIV carrier" },
      { id: "lupus", labelHe: "לופוס", labelEn: "Lupus" },
    ],
  },
  {
    id: "eyes",
    titleHe: "עיניים וראייה",
    titleEn: "Eyes and vision",
    options: [
      { id: "cataract", labelHe: "קטרקט", labelEn: "Cataract" },
      { id: "retina", labelHe: "בעיות רשתית / קרנית", labelEn: "Retina and cornea problems" },
      { id: "glaucoma", labelHe: "גלאוקומה", labelEn: "Glaucoma" },
      { id: "inflammation", labelHe: "דלקות עיניים", labelEn: "Inflammations of the eye" },
      { id: "strabismus", labelHe: "פזילה", labelEn: "Strabismus" },
      { id: "blindness", labelHe: "עיוורון", labelEn: "Blindness" },
    ],
  },
  {
    id: "heart",
    titleHe: "לב",
    titleEn: "Heart",
    options: [
      { id: "arrhythmia", labelHe: "הפרעות קצב", labelEn: "Cardiac arrhythmias" },
      { id: "disease", labelHe: "מחלת לב", labelEn: "Heart disease" },
      { id: "failure", labelHe: "אי ספיקת לב", labelEn: "Heart failure" },
      { id: "attack", labelHe: "התקף לב", labelEn: "Heart attack" },
      { id: "congenital", labelHe: "מום לב מולד", labelEn: "Congenital heart defect" },
      { id: "catheter", labelHe: "צנתור", labelEn: "Catheterization" },
      { id: "valves", labelHe: "מחלות מסתמים / בעיה אחרת", labelEn: "Heart valve diseases / other" },
    ],
  },
  {
    id: "vessels",
    titleHe: "כלי דם",
    titleEn: "Blood vessels",
    options: [
      { id: "varicose", labelHe: "דליות ברגליים", labelEn: "Varicose vein (legs)" },
      { id: "carotid", labelHe: "עורק הקרוטיד", labelEn: "Carotid artery" },
      { id: "coagulation", labelHe: "הפרעות קרישה", labelEn: "Coagulation disorders" },
      { id: "dvt", labelHe: "מחלת דם / DVT", labelEn: "Blood disease / DVT (Thrombosis)" },
      { id: "pvd", labelHe: "PVD", labelEn: "PVD (Peripheral Vascular Disease)" },
    ],
  },
  {
    id: "metabolic",
    titleHe: "מחלות מטבוליות",
    titleEn: "Metabolic diseases",
    options: [
      { id: "thyroid", labelHe: "בלוטת התריס", labelEn: "Thyroid gland" },
      { id: "lymph", labelHe: "בלוטות לימפה", labelEn: "Lymph node" },
      { id: "salivary", labelHe: "בלוטות רוק", labelEn: "Salivary gland" },
      { id: "sweat", labelHe: "בלוטות זיעה", labelEn: "Sweat gland" },
      { id: "pituitary", labelHe: "יותרת המוח", labelEn: "Pituitary gland" },
      { id: "diabetes", labelHe: "סוכרת", labelEn: "Diabetes" },
      { id: "hypertension", labelHe: "לחץ דם גבוה", labelEn: "Hypertension" },
      { id: "cholesterol", labelHe: "שומנים / כולסטרול גבוה", labelEn: "High fats / cholesterol" },
    ],
  },
  {
    id: "respiratory",
    titleHe: "מערכת הנשימה",
    titleEn: "Respiratory system",
    options: [
      { id: "asthma", labelHe: "אסתמה", labelEn: "Asthma" },
      { id: "tb", labelHe: "שחפת", labelEn: "Tuberculosis" },
      { id: "copd", labelHe: "COPD", labelEn: "COPD" },
      { id: "hayfever", labelHe: "קדחת השחת", labelEn: "Hay fever" },
      { id: "infections", labelHe: "זיהומים חוזרים / קוצר נשימה", labelEn: "Recurrent infections / shortness of breath" },
      { id: "pneumothorax", labelHe: "ריאה מכווצת", labelEn: "Collapsed lung (Pneumothorax)" },
      { id: "cf", labelHe: "סיסטיק פיברוזיס", labelEn: "Cystic Fibrosis" },
    ],
  },
  {
    id: "digestive",
    titleHe: "מערכת העיכול",
    titleEn: "Digestive system",
    options: [
      { id: "ulcer", labelHe: "כיב", labelEn: "Ulcer (duodenum / gastric)" },
      { id: "heartburn", labelHe: "צרבת", labelEn: "Heartburn" },
      { id: "crohn", labelHe: "קרוהן", labelEn: "Crohn's disease" },
      { id: "colitis", labelHe: "קוליטיס", labelEn: "Colitis" },
      { id: "reflux", labelHe: "רפלוקס", labelEn: "Reflux" },
      { id: "hemorrhoids", labelHe: "טחורים", labelEn: "Hemorrhoids" },
      { id: "fissure", labelHe: "פיסורה / פיסטולה", labelEn: "Fissure / Fistula" },
      { id: "obstruction", labelHe: "חסימת מעיים", labelEn: "Bowel obstruction" },
      { id: "pancreas", labelHe: "לבלב", labelEn: "Pancreatic diseases / infections" },
      { id: "esophagus", labelHe: "וושט", labelEn: "Esophagus" },
      { id: "gallbladder", labelHe: "כיס מרה / אבנים", labelEn: "Gallbladder / stones" },
    ],
  },
  {
    id: "liver",
    titleHe: "כבד",
    titleEn: "Liver",
    options: [
      { id: "jaundice", labelHe: "צהבת", labelEn: "Jaundice" },
      { id: "hepatitis", labelHe: "הפטיטיס B/C/D", labelEn: "Hepatitis B, C, D" },
      { id: "fatty", labelHe: "כבד שומני", labelEn: "Fatty liver" },
      { id: "cirrhosis", labelHe: "שחמת", labelEn: "Cirrhosis" },
    ],
  },
  {
    id: "hernia",
    titleHe: "בקע",
    titleEn: "Hernia",
    options: [
      { id: "diaphragm", labelHe: "בסרעפת", labelEn: "In the diaphragm" },
      { id: "navel", labelHe: "בטבור", labelEn: "In the navel" },
      { id: "right_groin", labelHe: "במפשעה ימין", labelEn: "In the right groin" },
      { id: "left_groin", labelHe: "במפשעה שמאל", labelEn: "In the left groin" },
    ],
  },
  {
    id: "kidney",
    titleHe: "כליות ודרכי שתן",
    titleEn: "Kidney and urinary tract",
    options: [
      { id: "infections", labelHe: "זיהומים חוזרים", labelEn: "Recurrent infections" },
      { id: "stones", labelHe: "אבנים", labelEn: "Kidney and urinary stones" },
      { id: "cysts", labelHe: "ציסטות", labelEn: "Kidney cysts" },
      { id: "anomalies", labelHe: "מומים בדרכי השתן", labelEn: "Anomalies of urinary tract" },
      { id: "failure", labelHe: "אי ספיקת כליות", labelEn: "Renal failure" },
    ],
  },
  {
    id: "joints",
    titleHe: "מפרקים ועצמות",
    titleEn: "Joints and bones",
    options: [
      { id: "arthritis", labelHe: "דלקת מפרקים", labelEn: "Arthritis" },
      { id: "gout", labelHe: "שיגדון", labelEn: "Gout" },
      { id: "back", labelHe: "גב / עמוד שדרה", labelEn: "Back / spine" },
      { id: "joints", labelHe: "מפרקים", labelEn: "Joints" },
      { id: "knees", labelHe: "ברכיים", labelEn: "Knees" },
    ],
  },
  {
    id: "skin",
    titleHe: "עור ומחלות מין",
    titleEn: "Skin and sex diseases",
    options: [
      { id: "tumors", labelHe: "גידולי עור", labelEn: "Skin tumors" },
      { id: "lesions", labelHe: "נגעי עור", labelEn: "Skin lesions" },
      { id: "psoriasis", labelHe: "פסוריאזיס", labelEn: "Psoriasis" },
      { id: "std", labelHe: "מחלות מין", labelEn: "Sexually transmitted diseases" },
      { id: "syphilis", labelHe: "עגבת", labelEn: "Syphilis" },
    ],
  },
  {
    id: "cancer",
    titleHe: "גידולים ממאירים / סרטן",
    titleEn: "Malignant tumors / diseases (cancer)",
    options: [{ id: "cancer", labelHe: "סרטן / גידול ממאיר", labelEn: "Malignant tumor / cancer" }],
  },
  {
    id: "women",
    titleHe: "לנשים",
    titleEn: "For women",
    womenOnly: true,
    options: [
      { id: "breasts", labelHe: "שדיים (כולל הגדלה)", labelEn: "Breasts (including enlargement)" },
      { id: "gyn", labelHe: "מערכת גינקולוגית / בעיה נשית", labelEn: "Gynecological / feminine problem" },
      { id: "cesarean", labelHe: "ניתוח קיסרי", labelEn: "Cesarean delivery" },
    ],
  },
  {
    id: "men",
    titleHe: "לגברים",
    titleEn: "For men",
    menOnly: true,
    options: [
      { id: "prostate", labelHe: "בעיות ערמונית", labelEn: "Prostate problems" },
      { id: "varicocele", labelHe: "דליות אשך / הידרוצלה", labelEn: "Varicocele / Hydrocele" },
    ],
  },
  {
    id: "mental",
    titleHe: "מחלות נפש",
    titleEn: "Mental illnesses",
    options: [
      {
        id: "mental",
        labelHe: "מחלה שאובחנה ע״י פסיכולוג / פסיכיאטר / רופא משפחה",
        labelEn: "Mental illness diagnosed by psychologist, psychiatrist or family physician",
      },
    ],
  },
  {
    id: "ent",
    titleHe: "אף, אוזן וגרון",
    titleEn: "Nose, ear and throat",
    options: [
      { id: "apnea", labelHe: "דום נשימה בשינה", labelEn: "Sleep apnea syndrome" },
      { id: "polyp", labelHe: "פוליפ באף", labelEn: "Nasal polyp" },
      { id: "sinusitis", labelHe: "סינוסיטיס", labelEn: "Sinusitis" },
    ],
  },
];
